In [1]:
import pandas as pd
s = pd.Series([1, 2, 3, 4, 5])
s.replace(1, 5)

0    5
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df.replace(0, 5)

   A  B  C
0  5  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [3]:
df.replace([0, 1, 2, 3], 4)

   A  B  C
0  4  5  a
1  4  6  b
2  4  7  c
3  4  8  d
4  4  9  e

In [4]:
df.replace([0, 1, 2, 3], [4, 3, 2, 1])

   A  B  C
0  4  5  a
1  3  6  b
2  2  7  c
3  1  8  d
4  4  9  e

In [5]:
s.replace([1, 2], method='bfill')

0    3
1    3
2    3
3    4
4    5
dtype: int64

In [6]:
df.replace({0: 10, 1: 100})

     A  B  C
0   10  5  a
1  100  6  b
2    2  7  c
3    3  8  d
4    4  9  e

In [7]:
df.replace({'A': 0, 'B': 5}, 100)

     A    B  C
0  100  100  a
1    1    6  b
2    2    7  c
3    3    8  d
4    4    9  e

In [8]:
df.replace({'A': {0: 100, 4: 400}})

     A  B  C
0  100  5  a
1    1  6  b
2    2  7  c
3    3  8  d
4  400  9  e

In [9]:
df = pd.DataFrame({'A': ['bat', 'foo', 'bait'],
                   'B': ['abc', 'bar', 'xyz']})
df.replace(to_replace=r'^ba.$', value='new', regex=True)

      A    B
0   new  abc
1   foo  new
2  bait  xyz

In [10]:
df.replace({'A': r'^ba.$'}, {'A': 'new'}, regex=True)

      A    B
0   new  abc
1   foo  bar
2  bait  xyz

In [11]:
df.replace(regex=r'^ba.$', value='new')

      A    B
0   new  abc
1   foo  new
2  bait  xyz

In [12]:
df.replace(regex={r'^ba.$': 'new', 'foo': 'xyz'})

      A    B
0   new  abc
1   xyz  new
2  bait  xyz

In [13]:
df.replace(regex=[r'^ba.$', 'foo'], value='new')

      A    B
0   new  abc
1   new  new
2  bait  xyz

In [14]:
s = pd.Series([10, 'a', 'a', 'b', 'a'])

In [15]:
s.replace({'a': None})

0      10
1    None
2    None
3       b
4    None
dtype: object

In [16]:
s.replace('a')

0    10
1    10
2    10
3     b
4     b
dtype: object

In [17]:
s.replace('a', None)

0    10
1    10
2    10
3     b
4     b
dtype: object