In [1]:
import pandas as pd
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})
df1

  lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

In [2]:
df1.merge(df2, left_on='lkey', right_on='rkey')

  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

In [3]:
df1.merge(df2, left_on='lkey', right_on='rkey',
          suffixes=('_left', '_right'))

  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  foo           5  foo            5
3  foo           5  foo            8
4  bar           2  bar            6
5  baz           3  baz            7

In [6]:
df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
df1

     a  b
0  foo  1
1  bar  2

In [7]:
df2

     a  c
0  foo  3
1  baz  4

In [8]:
df1.merge(df2, how='inner', on='a')

     a  b  c
0  foo  1  3

In [9]:
df1.merge(df2, how='left', on='a')

     a  b    c
0  foo  1  3.0
1  bar  2  NaN

In [10]:
df1 = pd.DataFrame({'left': ['foo', 'bar']})
df2 = pd.DataFrame({'right': [7, 8]})
df1

  left
0  foo
1  bar

In [11]:
df2

   right
0      7
1      8

In [12]:
df1.merge(df2, how='cross')

  left  right
0  foo      7
1  foo      8
2  bar      7
3  bar      8